# Generated by Django 6.1.1 on 2026-10-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status_interview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
